export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";

export const SET_SUCCESS_MESSAGE = "SET_SUCCESS_MESSAGE";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const DATA_LIST_REQUEST = "DATA_LIST_REQUEST";
export const DATA_LIST_SUCCESS = "DATA_LIST_SUCCESS";
export const DATA_LIST_FAILED = "DATA_LIST_FAILED";

export const DATA_UPDATE_SUCCESS = "DATA_UPDATE_SUCCESS";

export const DATA_CREATE_REQUEST = "DATA_CREATE_REQUEST";
export const DATA_CREATE_SUCCESS = "DATA_CREATE_SUCCESS";
export const DATA_CREATE_FAIL = "DATA_CREATE_FAIL";
export const DATA_CREATE_RESET = "DATA_CREATE_RESET";

export const DATA_DELETE_REQUEST = "DATA_DELETE_REQUEST";
export const DATA_DELETE_SUCCESS = "DATA_DELETE_SUCCESS";
export const DATA_DELETE_FAIL = "DATA_DELETE_FAIL";
export const DATA_DELETE_RESET = "DATA_DELETE_RESET";
